### ISSUE TITLE
4.02 Dashboard Movimentação Estoque - Layout

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#10]
### Menu Superior
- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página

- [ ]  Botão Voltar com alinhamento superior direito e background: #531D62
- [ ]  Background Imagem Placa

**Filtros** - combobox
- [ ] Fornecedor
- [ ]  Categoria
- [ ]  Marca
- [ ]  Modelo
- [ ] Gráfico Itens Consumidos
- [ ] Alinhamento dos filtros na parte superior

**Gráficos**
1) Gráfico Itens 
- [ ]  Gráfico com alinhamento a esquerda
- [ ]  Título Centralizado: Itens
- [ ] Link Anos com alnihamento superior esquerdo
- [ ] Icone busca com alinhamento superior direito
- [ ] Gráfico de barra com entradas, saídas e total
- [ ] Filtro dos meses na parte inferior com opção para escolha simultânea
- [ ] Background branco
- [ ] Borda do background: #707070
- [ ] Sombra background: #707070 x 5 y 5 d 1

2) Gráfico Valores
- [ ]  Gráfico com alinhamento a esquerda
- [ ]  Título Centralizado: Valores
- [ ] Link Anos com alnihamento superior esquerdo
- [ ] Icone busca com alinhamento superior direito
- [ ] Gráfico de barra com entradas, saídas e total
- [ ] Filtro dos meses na parte inferior com opção para escolha simultânea
- [ ] Background branco
- [ ] Borda do background: #707070
- [ ] Sombra background: #707070 x 5 y 5 d 1

**Tabela**

- [ ] Alinhamento a direita
- [ ] Cabeçalho da Tabela: Itens / Valores
- [ ] Colunas da tabela: Mês / Entradas (itens) / Saídas (itens) / Total (itens) / Entradas (valores) / Saídas (valores) / Total (valores)
- [ ] Rodapé da tabela com acumulado do ano
- [ ] Bakcground itens: roxo: #531D62 transparência 23%
- [ ] Bakcground valores: roxo #531D62 transparência 13%
- [ ] Bakcground mês: roxo #531D62 transparência 13%
- [ ] Bakcground última linha: roxo #531D62
- [ ] Background da tabela: branco
- [ ] Borda do background da tabela: #707070
- [ ] Sombra background da tabela: #707070 x 5 y 5 d 1

### Rodapé
- [ ] Logo DevQore
![04 02 Dashboard Movimentação Estoque](https://user-images.githubusercontent.com/72522695/102368451-a1adcc00-3f99-11eb-813a-d943baeccae1.png)
