### ISSUE TITLE
4.03 Dashboard Alerta Nível de Estoque

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#11]
### Menu Superior

- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página

- [ ]  Botão Voltar com alinhamento superior direito e background: #531D62
- [ ]  Background Imagem Placa

**Tabela**
Informações Gerais:
- [ ] Alinhamento centralizado
- [ ] Background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] Botão de Paginação
- [ ] Subtítulo: Alerta Nível de Estoque / Alerta Validade de Estoque
- [ ] Cor Fonte: #06024C

Tabela - Alerta Nível de Estoque:
- [ ]  Colunas da tabela (Cor Fonte: #06024C): Imagem / ID / Código / Categoria / Marca / Modelo / Descrição / Qte / Média / Alerta / Status
- [ ]  linha em formato de card 
- [ ]  borda da linha Card background:  #707070
- [ ] Sombra da linha Card:  #707070  x 5 y 5 d 1
- [ ] Icone Image
- [ ] Icone Status (amarelo: #7E7E7E vermelho: #D43042 preto: #000000)
- [ ] Icone menu linha Card

Tabela - Alerta Validade de Estoque:
- [ ]  Colunas da tabela (Cor Fonte: #06024C): Imagem / ID / Código / Categoria / Marca / Modelo / Descrição / Qte / Validade / Alerta / Status
- [ ]  linha em formato de card 
- [ ]  borda da linha Card background:  #707070
- [ ] Sombra da linha Card:  #707070  x 5 y 5 d 1
- [ ] Icone Image
- [ ] Icone Status (amarelo: #7E7E7E vermelho: #D43042 preto: #000000)
- [ ] Icone menu linha Card

### Rodapé
 - [ ] Logo DevQore

![04 03 Dashboard Alerta Estoque2](https://user-images.githubusercontent.com/72522695/102371395-e8e98c00-3f9c-11eb-9631-b25ddc9a7652.png)
![04 03 Dashboard Alerta Nivel Estoque](https://user-images.githubusercontent.com/72522695/102371400-ea1ab900-3f9c-11eb-8d9f-8965175188b4.png)
