### ISSUE TITLE
4.04 Dashboard Empréstimos

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#12]
### Menu Superior

- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página

- [ ]  Botão Voltar com alinhamento superior direito e background: #531D62
- [ ]  Background Imagem Placa

**Tabela**
- [ ] Alinhamento centralizado
- [ ] Background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] Botão de Paginação
- [ ] Subtítulo: Empréstimo
- [ ] Cor Fonte: #06024C
- [ ] Colunas da tabela (Cor Fonte: #06024C): Imagem / Data / Registro / ID / Código / Categoria / Marca / Modelo / De / Para / Qte / Prazo / Status
- [ ]  linha em formato de card 
- [ ]  borda da linha Card background:  #707070
- [ ] Sombra da linha Card:  #707070  x 5 y 5 d 1
- [ ] Icone Imagem
- [ ] Icone Alerta
- [ ] Icone Alerta Novo
- [ ] Icone menu linha Card

Tabela - Alerta Validade de Estoque:
- [ ]  Colunas da tabela (Cor Fonte: #06024C): Imagem / ID / Código / Categoria / Marca / Modelo / Descrição / Qte / Validade / Alerta / Status
- [ ]  linha em formato de card 
- [ ]  borda da linha Card background:  #707070
- [ ] Sombra da linha Card:  #707070  x 5 y 5 d 1
- [ ] Icone Image
- [ ] Icone Status (amarelo: #7E7E7E vermelho: #D43042 preto: #000000)
- [ ] Icone menu linha Card

### Rodapé
 - [ ] Logo DevQore
 
![04 Dashboard Emprestimos](https://user-images.githubusercontent.com/72522695/102372337-dcb1fe80-3f9d-11eb-9938-4d93c95da160.png)
