### ISSUE TITLE
4.05 Dashboard Solicitacao Retirada

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#13]
### Menu Superior

- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página

- [ ]  Botão Voltar com alinhamento superior direito e background: #531D62
- [ ]  Background Imagem Placa

**Tabela**

- [ ] Título alinhado a esquerda: Solicitações de Retirada
- [ ] Cor Fonte: #06024C
- [ ] Alinhamento da tabela centralizado
- [ ] Background da tabela branco
- [ ] Borda do background da tabela:  #707070
- [ ] Sombra background da tabela:  #707070  x 5 y 5 d 1
- [ ] Formulário de Busca
- [ ] Botão de busca: Data
- [ ] Botão de busca: Usuário
- [ ] Botão de busca: ID
- [ ] Botão de busca: Código
- [ ] Botão de busca: Categoria
- [ ] Botão de busca: Marca
- [ ] Botão de busca: Modelo
- [ ] Botão de busca: Fornecedor
- [ ] Botão de busca: Descrição
- [ ] Botão de busca: Encapsulamento
- [ ] Botão de busca: Posição
- [ ] Botão de busca: Valor
- [ ] Botão de Paginação
- [ ]  dados da linha card: Nome / Data / Descrição / Categoria / Modelo / Fornecedor / Código / ID / Venda / OS / NF / Qte
- [ ]  linha em formato de card 
- [ ]  borda da linha Card background:  #707070
- [ ] Sombra da linha Card:  #707070  x 5 y 5 d 1
- [ ] Icone Imagem
- [ ] Icone menu linha Card

### Rodapé
 - [ ] Logo DevQore

![04 05 Dashboard Solicitacao Retiradas](https://user-images.githubusercontent.com/72522695/102373741-4bdc2280-3f9f-11eb-9a6e-a64889c7c309.png)
