### ISSUE TITLE
5.00 Perfil Usuário

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#14]
### Menu Superior

- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página

- [ ]  Botão Voltar com alinhamento superior direito e background: #531D62
- [ ]  Background Imagem Placa
- [ ]  Icone Busca
- [ ] Formulário Busca

**Página no Estado Hoover**
- [ ] Icone Usuário cor #7E7E7E
- [ ] Nome Usuário cor #7E7E7E
- [ ] CPF / CNPJ cor #7E7E7E
- [ ] Cargo / Função cor#7E7E7E

**Página no Estado Padrão**
- [ ] Icone Usuário cor #06024C
- [ ] Nome Usuário cor #06024C
- [ ] CPF / CNPJ cor #06024C
- [ ] Cargo / Função cor #06024C

**Cards**
1) Card Usuários
- [ ] Alinhamento a esquerda
- [ ] Nome e ícone dos usuários
- [ ] Barra de rolagem
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

2) Card Informações Gerais
2.1 Estado Hoover 
- [ ] Texto: Sem informações
- [ ] Cor do Texto: #7E7E7E
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

2.2 Estado Padrão
- [ ] Texto: Informações Gerais (list box): Endereço / Bairro / Cidade / Estado / Telefones / Emai / Perfil / ID / Data Cadastro
- [ ] icone Logo Info Gerais
- [ ] Cor do Texto: #06024C
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

3) Card Solicitação Pendente
3.1 Estado Hoover 
- [ ] Texto: Sem informações
- [ ] Cor do Texto: #7E7E7E
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

3.2 Estado Padrão
- [ ] Quantidade de Solicitações -  Bold, Cor: #06024C
- [ ] Texto Solicitações Retiradas Pendentes - Regular,  Cor: #06024C
- [ ] icone Solicitação Pendente - Cor: #06024C
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

4) Card Itens Retirados
4.1 Estado Hoover 
- [ ] Texto: Sem informações
- [ ] Cor do Texto: #7E7E7E
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

4.2 Estado Padrão
- [ ] Quantidade de Itens Retirados-  Bold, Cor: #06024C
- [ ] Texto: Itens Retirados - Regular,  Cor: #06024C
- [ ] icone Itens - Cor: #06024C
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

5) Card Homem-Hora
5.1 Estado Hoover 
- [ ] Texto: Sem informações
- [ ] Cor do Texto: #7E7E7E
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

5.2 Estado Padrão
- [ ] Valor Homem - Hora -  Bold, Cor: #06024C
- [ ] Texto: Homem - Hora - Regular,  Cor: #06024C
- [ ] icone $ - Cor: #06024C
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

6) Card Tabela
5.1 Estado Hoover 
- [ ] Subtítulos: Solicitações de Retirada / Entradas / Saídas - cor #7E7E7E
- [ ] Background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] linhas Cards - Background branco
- [ ] linhas Cards - Borda do background:  #707070
- [ ] linhas Cards - Sombra do background:  #707070 x 5 y 5 d 1
- [ ] linhas Cards - Texto: Sem Informações cor #7E7E7E

6.2 Estado Padrão
6.2.1 Informações Gerais
- [ ] Background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] Paginação
- [ ] Botão Buscar
- [ ] Subtítulos: Solicitações de Retirada / Entradas / Saídas

6.2.2) Solicitações de Retirada
- [ ] Linhas Card Sol. Retirada - Nome Solicitante / Foto Solicitante / Descrição do Item / Categoria / Modelo / Data / ID / Codigo / Venda / OS / NF / Fornecedor /Quantidade
- [ ] Linhas Card Sol Retirada: Background branco
- [ ] Linhas Card Sol Retirada: Borda do background:  #707070
- [ ] Linhas Card Sol Retirada: Sombra background:  #707070  x 5 y 5 d 1
- [ ] Linhas Card Sol Retirada: Efeito Hoover
- [ ] Menu Linha Cards
- [ ] Maximizar

6.2.3) Entradas
- [ ] Linhas Card Entrada - Nome Solicitante / Foto Solicitante / Descrição do Item / Categoria / Modelo / Data / ID / Codigo / OS / NF / Fornecedor / Quantidade
- [ ] Menu Linha Cards
- [ ] Icone Entradas
- [ ] Paginação
- [ ] Botão Buscar
- [ ] Maximizar

6.2.4) Retiradas
- [ ] Linhas Card Entrada - Nome Solicitante / Foto Solicitante / Descrição do Item / Categoria / Modelo / Data / ID / Codigo / OS / Venda / NF / Fornecedor / Quantidade
- [ ] Menu Linha Cards
- [ ] Icone Retiradas
- [ ] Paginação
- [ ] Botão Buscar
- [ ] Maximizar

### Rodapé
 - [ ] Logo DevQore
 
![05 - Perfil Usuário - 02](https://user-images.githubusercontent.com/72522695/102376608-93b07900-3fa2-11eb-86fd-47f8b6b94477.png)
