### ISSUE TITLE
6.00 Perfil Parceiro

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#15]
### Menu Superior

- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página

- [ ]  Botão Voltar com alinhamento superior direito e background: #531D62
- [ ]  Background Imagem Placa
- [ ]  Icone Busca
- [ ]  Formulário Busca

**Página no Estado Hoover**
- [ ] Icone Parceiro cor #7E7E7E
- [ ] Nome Parceiro cor #7E7E7E
- [ ] CPF / CNPJ cor #7E7E7E
- [ ] Cargo / Função cor #7E7E7E
- [ ] Texto Ver Mais cor #7E7E7E
- [ ] Linha Ver Mais cor #7E7E7E

**Página no Estado Padrão**
- [ ] Icone Parceiro cor #06024C
- [ ] Nome Parceiro cor #06024C
- [ ] CPF / CNPJ cor #06024C
- [ ] Cargo / Função cor #06024C
- [ ] Texto Ver Mais cor #06024C
- [ ] Linha Ver Mais cor #7E7E7E

**Cards**
1) Card Pareiros
- [ ] Alinhamento a esquerda
- [ ] Nome e ícone dos usuários
- [ ] Barra de rolagem
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

2) Card Informações Gerais
2.1 Estado Hoover 
- [ ] Texto: Sem informações
- [ ] Cor do Texto: #7E7E7E
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

2.2 Estado Padrão
- [ ] Texto: Informações Gerais (list box): Endereço / Bairro / Cidade / Estado / Telefones / Emai / Perfil / ID / Data Cadastro
- [ ] icone Logo Info Gerais
- [ ] Cor do Texto: #06024C
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

3) Card Última Compra
3.1 Estado Hoover 
- [ ] Texto: Sem informações
- [ ] Cor do Texto: #7E7E7E
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

3.2 Estado Padrão
- [ ] Data Última Solicitação -  Bold, Cor: #06024C
- [ ] Texto Última Soicitação - Regular,  Cor: #06024C
- [ ] icone Calendário - Cor: #06024C
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

4) Card Itens do Parceiro
4.1 Estado Hoover 
- [ ] Texto: Sem informações
- [ ] Cor do Texto: #7E7E7E
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

4.2 Estado Padrão
- [ ] Quantidade de Itens no Estoque-  Bold, Cor: #06024C
- [ ] Texto: Itens em Estoque- Regular,  Cor: #06024C
- [ ] icone Itens - Cor: #06024C
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

5) Card Cliente
5.1 Estado Hoover 
- [ ] Texto: Sem informações
- [ ] Cor do Texto: #7E7E7E
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

5.2 Estado Padrão
- [ ] Icone Parceiro Cor: #06024C
- [ ] Texto: Cliente - Bold,  Cor: #06024C
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

6) Card Fornecedor
5.1 Estado Hoover 
- [ ] Texto: Sem informações
- [ ] Cor do Texto: #7E7E7E
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

5.2 Estado Padrão
- [ ] Icone Fornecedor Cor: #06024C
- [ ] Texto: Cliente - Bold,  Cor: #06024C
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

6) Card Aquisição de Itens - Calendário do Ano
6.1 Estado Hoover 
- [ ] Todas as quadrículas em branco e contorno cinza: #707070
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 
- [ ] Lengenda 0 a max cor branco
- [ ] Texto Legenda 0 e max: cor #7E7E7E
- [ ] Colunas (meses) cor #7E7E7E
- [ ] Linhas dias da semana cor #7E7E7E

6.2 Estado Padrão
- [ ] Quadrículas preenchidas conforme legenda
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 
- [ ] Lengenda 0 a max degrade linear 0º menor (#FFFFFF) para maior: #531D62 
- [ ] Texto Legenda 0 e max: cor #06024C
- [ ] Colunas (meses) cor #06024C
- [ ] Linhas dias da semana cor #06024C

Card Entradas
- [ ] Linhas Card Entrada - Nome Solicitante / Foto Solicitante / Descrição do Item / Categoria / Modelo / Data / ID / Codigo / OS / NF / Fornecedor / Quantidade
- [ ] Icone Entradas
- [ ] Paginação: Ver Mais
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

### Rodapé
 - [ ] Logo DevQore

![06 - Perfil Parceiro 3](https://user-images.githubusercontent.com/72522695/102378808-f145c500-3fa4-11eb-9e5b-320ea8c9ee8b.png)
![06 - Perfil Parceiro](https://user-images.githubusercontent.com/72522695/102378813-f1de5b80-3fa4-11eb-9e90-b0f05c0c9e73.png)
