### ISSUE TITLE
7.00 Material

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#16]
### Menu Superior

- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página

- [ ]  Botão Voltar com alinhamento superior direito e background: #531D62
- [ ]  Background Imagem Placa
- [ ]  Icone Imagem Item
- [ ]  Descrição do Material - Bold, cor #06024C
- [ ]  ID - Bold, cor #06024C
- [ ] Categoria - Bold, cor #06024C 
- [ ] Marca- Bold, cor #06024C
- [ ] Código - Bold, cor #06024C
- [ ] Encapsulamento - Bold, cor #06024C
- [ ] Modelo - Bold, cor #06024C

**Cards**
1) Card Fornecedores
- [ ] Alinhamento a esquerda
- [ ] Título Alinha a Esquerda: Fornecedores, tam 25 Bold, cor #06024C
- [ ] Nome e ícone dos fornecedores
- [ ] Barra de rolagem
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] link buscar fornecedor na web
- [ ] icone Web

2) Card Histórico
- [ ] Título: Histórico - tam 25 Bold, cor #06024C
- [ ] Subtítulo itens / Valores - tam 30 Bold, cor #06024C
- [ ] gráfico de linha de itens com informações de Estoque / Entrada / Saída
- [ ] gráfico de linha de valores com informações de Estoque / Entrada / Saída
- [ ] Menu Gráfico alinhado a dierita superior
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

3) Card Itens em Estoque
- [ ] Quantidade em Estoque -  tam 70, Bold, Cor: #06024C
- [ ] Valor em Estoque -  tam 70, Bold, Cor: #06024C
- [ ] Valor/unid - tam 25, Regular,  Cor: #06024C
- [ ] icone Item - Cor: #531D62
- [ ] icone Valor - cor #531D62
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

4) Card Tabela Histórico
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] Boatão de Paginação
- [ ] Subtituilos: Entradas / Saídas tam 30, Bold, Cor: #06024C
- [ ] Colunas: Datas / Regsitro / Fornecedor / Qte / Valor por unid / Total / NF tam 25, Bold, Cor: #06024C
- [ ] linhas padrão: texto tam 15, Regular, Cor: #06024C
- [ ] linhas efeito hoover: texto Cor Branco, fundo Azul Cor: #06024C

### Rodapé
 - [ ] Logo DevQore
 
![07 - Material](https://user-images.githubusercontent.com/72522695/102380788-1c311880-3fa7-11eb-8340-ace4823598bd.png)
