### ISSUE TITLE
8.00 Equipamento

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#17]
### Menu Superior

- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página

- [ ]  Botão Voltar com alinhamento superior direito e background: #531D62
- [ ]  Background Imagem Placa
- [ ]  Icone Imagem Item
- [ ]  Descrição do Material - Bold, cor #06024C
- [ ]  ID - Bold, cor #06024C
- [ ] Categoria - Bold, cor #06024C 
- [ ] Marca- Bold, cor #06024C
- [ ] Código - Bold, cor #06024C
- [ ] Modelo - Bold, cor #06024C

**Cards**
1) Card Fornecedores
- [ ] Alinhamento a esquerda
- [ ] Título Alinha a Esquerda: Fornecedores, tam 25 Bold, cor #06024C
- [ ] Nome e ícone dos fornecedores
- [ ] Barra de rolagem
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] link buscar fornecedor na web
- [ ] icone Web

2) Card Status
- [ ] Título: Status Atual (centralizado superior) - tam 20 Bold, cor #06024C
- [ ] Situação - tam 20 bold, cor #06024C
- [ ] De - tam 20 Bold, cor #06024C
- [ ] Para - tam 20 Bold, cor #06024C
- [ ] Valor - tam 20 Bold, cor #06024C
- [ ] Observações - tam 20 Bold, cor #06024C
- [ ] Prazo - tam 20 Bold, cor #06024
- [ ] Gráfico de evolução: data início / hoje / prazo 
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

3) Card Equipamentos em Estoque
- [ ] Quantidade em Estoque -  tam 70, Bold, Cor: #06024C
- [ ] Valor em Estoque -  tam 70, Bold, Cor: #06024C
- [ ] Valor/unid - tam 25, Regular,  Cor: #06024C
- [ ] icone Item - Cor: #531D62
- [ ] icone Valor - cor #531D62
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

4) Card Tabela Histórico
- [ ] background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] Boatão de Paginação
- [ ] Subtituilo: Empréstimos
- [ ] Colunas: Datas / Regsitro / De / Para / Qte / Prazo / Entrega / Status / Observações / Valor -  tam 25, Bold, Cor: #06024C
- [ ] linhas padrão: texto tam 15, Regular, Cor: #06024C
- [ ] linhas efeito hoover: texto Cor Branco, fundo Azul Cor: #06024C

### Rodapé
 - [ ] Logo DevQore

![08 - Equipamento](https://user-images.githubusercontent.com/72522695/102381356-dcb6fc00-3fa7-11eb-9852-a82ede5bd781.png)
