### ISSUE TITLE
9.00 - Cadastro de Usuário

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#18]
### Menu Superior

- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página

- [ ]  Botão Voltar com alinhamento superior direito e background: #531D62
- [ ]  Background Imagem Placa
- [ ]  Icone Imagem Item
- [ ] Formulário Nome / Razão Social
- [ ] Formulário Nome Fantasia
- [ ] Formulário CPF / CNPJ
- [ ] Formulário CEP
- [ ] Formulário Endereço
- [ ] Formulário Bairro
- [ ] Formulário Cidade
- [ ] Combobox - Estado
- [ ] Formulário País
- [ ] Formulário Telefone 1
- [ ] Formulário Telefone 2
- [ ] Formulário Email
- [ ] Formulário Site
- [ ] Formulário Observações
- [ ] Formulário Usuário
- [ ] Formulário Senha
- [ ] Combobox Perfil
- [ ] Data Admissão
- [ ] Formulário Cargo/Atividade
- [ ] Formulário Homem-Hora
- [ ] Botão Cadastrar

**Confirmação de Cadastro realizado com sucesso**
- [ ] Background cinza #7E7E7E transparência 61%
- [ ] Quadro da Mensagem bakcground branco transparência 76%
- [ ] Texto: Cadastro de Usuário Realizado com Sucesso!!
- [ ] Botão Voltar alinhado no topo e a direita

### Rodapé
 - [ ] Logo DevQore
![09 - Cadastro de Usuário](https://user-images.githubusercontent.com/72522695/102407556-0d5c5d00-3fcb-11eb-963c-cb313c6cd9d3.png)
![09 - Cadastro de Usuário 02](https://user-images.githubusercontent.com/72522695/102407590-1b11e280-3fcb-11eb-896d-b76d6a677314.png)
