### ISSUE TITLE
10.00 Cadastro de Parceiro

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#19]
### Menu Superior

- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página

- [ ]  Botão Voltar com alinhamento superior direito e background: #531D62
- [ ]  Background Imagem Placa
- [ ]  Icone Imagem Item
- [ ] Formulário Nome / Razão Social
- [ ] Formulário Nome Fantasia
- [ ] Formulário CPF / CNPJ
- [ ] Formulário CEP
- [ ] Formulário Endereço
- [ ] Formulário Bairro
- [ ] Formulário Cidade
- [ ] Combobox - Estado
- [ ] Formulário País
- [ ] Formulário Telefone 1
- [ ] Formulário Telefone 2
- [ ] Formulário Email
- [ ] Formulário Site
- [ ] Formulário Observações
- [ ] Formulário Cargo/Atividade
- [ ] Formulário Homem-Hora
- [ ] Card Método de Pagamento
- [ ] Card Tipo de Parceiro
- [ ] Botão Cadastrar

**Confirmação de Cadastro realizado com sucesso**
- [ ] Background cinza #7E7E7E transparência 61%
- [ ] Quadro da Mensagem bakcground branco transparência 76%
- [ ] Texto: Cadastro de Parceiro 

Realizado com Sucesso!!
- [ ] Botão Voltar alinhado no topo e a direita

### Rodapé
 - [ ] Logo DevQore

![10 - Cadastro de Parceiro](https://user-images.githubusercontent.com/72522695/102408399-43e6a780-3fcc-11eb-979c-60d5ec9e06af.png)
![10 - Cadastro de Parceiro 2](https://user-images.githubusercontent.com/72522695/102408429-5234c380-3fcc-11eb-9cdd-85f4329c04f8.png)
