### ISSUE TITLE
11.00 Cadastro de Componente e Equipamento

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#20]
### Menu Superior

- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página

- [ ] Título Cadastro
- [ ]  Botão Voltar com alinhamento superior direito e background: #531D62
- [ ]  Background Imagem Placa
- [ ]  Icone Imagem Item
- [ ] Combobox Componente
- [ ] Combobox Categoria
- [ ] Combobox Marca
- [ ] Combobox Modelo
- [ ] Combobox Fornecedor
- [ ] Combobox Unidade
- [ ] Formulário Código
- [ ] Formulário Encapsulamento
- [ ] Formulário Descrição
- [ ] Formulário Observação
- [ ] Formulário Prazo de Entrega
- [ ] Formulário Valor de Compra
- [ ] Formulário Valor de Venda
- [ ] Formulário Valor de Aluguel
- [ ] Card Tipo de Parceiro
- [ ] Botão Cadastrar

### Confirmação de Novo Item Cadastrado

- [ ] Background cinza #7E7E7E transparência 61%
- [ ] Quadro da Mensagem bakcground branco transparência 76%

**Cabeçalho da mensagem** 

- [ ] Novo Item Cadastrado - texto em branco tam 50 Bold, background em azul (#06024C)
- [ ] ID  - texto em branco tam 50 Bold, background em roxo (#531D62)

**Corpo da Mensagem**

- [ ] Imagem do objeto alinhado a esquerda superior
- [ ] Descrição alinhado a esquerda meio superior
- [ ] Observações alinhado a esquerda meio inferior
- [ ] Prazo de Entrega alinhada a esquerda inferior

- [ ] Tipo, tópico em azul (#06024C) 35 Semibold / resposta em roxo (#531D62) 35 Regular
- [ ] Código, tópico em azul (#06024C) 35 Semibold / resposta em roxo (#531D62) 35 Regular
- [ ] Linha divisória 1 com símbolo de Diodo no meio

- [ ] Categoria, tópico em azul (#06024C) 35 Semibold / resposta em roxo (#531D62) 35 Regular
- [ ] Marca, tópico em azul (#06024C) 35 Semibold / resposta em roxo (#531D62) 35 Regular
- [ ] Modelo, tópico em azul (#06024C) 35 Semibold / resposta em roxo (#531D62) 35 Regular
- [ ] Fornecedor, tópico em azul (#06024C) 35 Semibold / resposta em roxo (#531D62) 35 Regular
- [ ] Unidade, tópico em azul (#06024C) 35 Semibold / resposta em roxo (#531D62) 35 Regular
- [ ] Linha divisória 2 com símbolo de Diodo no meio

- [ ] Valor de Compra, tópico em azul (#06024C) 35 Semibold / resposta em roxo (#531D62) 35 Regular
- [ ] Valor de Venda, tópico em azul (#06024C) 35 Semibold / resposta em roxo (#531D62) 35 Regular
- [ ] Valor de Aluguel, tópico em azul (#06024C) 35 Semibold / resposta em roxo (#531D62) 35 Regular
- [ ] Linha divisória 3 com símbolo de Diodo no meio

- [ ] Botão Cancelar alinhado à esquerda
- [ ] Botão confirmar alinhado à direita

### Rodapé
 - [ ] Logo DevQore

![11 - Cadastro de Componente e Equipamento](https://user-images.githubusercontent.com/72522695/102410102-d425ec00-3fce-11eb-8604-70672c512fe3.png)
![11 - Cadastro de Componente e Equipamento 2](https://user-images.githubusercontent.com/72522695/102410111-d720dc80-3fce-11eb-9392-de96cca6287c.png)
