### ISSUE TITLE
12 - Busca

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#21]
### Menu Superior

- [ ] Título: Escolha de Itens - 50 Bold roxo (#531D62) alinha a esquerda superior
- [ ] Botão Voltar alinhado a direita superior
- [ ] Campo Busca
- [ ] Icone Busca
- [ ] Botão de busca por ID
- [ ] Botão de busca por Código
- [ ] Botão de busca por Categoria
- [ ] Botão de busca por Marca
- [ ] Botão de busca por Modelo
- [ ] Botão de busca por Fornecedor
- [ ] Botão de busca por Descrição
- [ ] Botão de busca por Encapsulamento
- [ ] Botão de busca por Posição
- [ ] Botão de busca por Valor

###  Corpo da Página

**Tabela Componentes / Equipamentos **

- [ ] tabela alinhada a esquerda
- [ ] background branco
- [ ] borda do background #707070
- [ ] sombra do background #707070 x 5 y 5 d 1
- [ ] Subtitulos: Componentes / Equipamentos -Texto azul (#06024C) tam 25 BOLD
- [ ] Paginação no canto inferior direito

1) Dados da Tabela Componente

- [ ] Cabeçalho: Imagem / ID / Código / Categoria / Marca / Modelo / Fornecedor / Descrição / Encapsulamento / Estoque / Posição / Valor Médio Unidade / Quantidade - Texto azul (#06024C) tam 20 BOLD
- [ ] Linha em formato de CARD com background branco, borda cinza #707070 e sombra #707070 x 5 y 5 d 1 
- [ ] Texto da Linha Card azul (#06024C) tam 15 Regular
- [ ] Icone Menu Card
- [ ] Icone + (adicionar)
- [ ] Icone - (remover)

2) Dados da Tabela Equipamentos

- [ ] Cabeçalho: Imagem / ID / Código / Categoria / Modelo / De / Para / Descrição / Tipo / Início / Fim / Prazo / Quantidade - Texto azul (#06024C) tam 20 BOLD
- [ ] Linha em formato de CARD com background branco, borda cinza #707070 e sombra #707070 x 5 y 5 d 1 
- [ ] Texto da Linha Card azul (#06024C) tam 15 Regular
- [ ] Icone Menu Card
- [ ] Icone + (adicionar)
- [ ] Icone - (remover)

**Quadro Itens Selecionados**

Estado Padrão
- [ ] background branco
- [ ] borda do background #707070
- [ ] sombra do background #707070 x 5 y 5 d 1

Estado Hover
- [ ] background branco
- [ ] borda do background #707070
- [ ] sombra do background #707070 x 5 y 5 d 1
- [ ] Botão cancelar item
- [ ] MiniCard com ID, Codigo, Imagem, Descrição e Quantidade
- [ ] MiniCard background branco
- [ ] MiniCard borda do background #707070
- [ ] MiniCard sombra do background #707070 x 5 y 5 d 1

**Botões**

- [ ] Botão Adicionar alinhado a direita
- [ ] Botão Pedido de Compra alinhado à esquerda na parte inferior
- [ ] Botão Entrada de Material alinhado ao meio esquerdo na parte inferior
- [ ] Botão Saída de Material alinhado ao meio direito na parte inferior
- [ ] Botão Empréstimo alinhado à direita na parte inferior

### Rodapé
- [ ] Logo DevQore

![12 - Busca – 3](https://user-images.githubusercontent.com/72522695/102412775-b195d200-3fd2-11eb-85a6-337e5bdd7dcc.png)
![12 - Busca](https://user-images.githubusercontent.com/72522695/102412781-b2c6ff00-3fd2-11eb-9961-25b5ff847aa5.png)
![12 - Busca – 1](https://user-images.githubusercontent.com/72522695/102412784-b2c6ff00-3fd2-11eb-99ba-35e0c054d85a.png)
![12 - Busca – 2](https://user-images.githubusercontent.com/72522695/102412785-b35f9580-3fd2-11eb-85c2-d73a6f91e6e5.png)
