### ISSUE TITLE
13 Compra de Material

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#22]
### Menu Superior

- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página

- [ ] Background Imagem Placa
- [ ] Linha divisória de página (centro da página)
- [ ] Icone WEB
- [ ] Texto Buscar novos fornecedores na WEB - 25 Bold azul cor #06024C

**Card Material**

- [ ] background branco 
- [ ] borda background #707070
- [ ] sombra background #707070 x5 y 5 d 1
- [ ] Título Compra Material - 50 Bold azul cor #06024C
- [ ] LogoImagem
- [ ] Campo ID
- [ ] Campo Código
- [ ] Campo Encapsulamento
- [ ] Campo Categoria
- [ ] Campo Marca
- [ ] Campo Modelo
- [ ] Campo Descrição
- [ ] Botão Voltar alinhado à direita superior
- [ ] Linha divisória de página

**Card Valor da Unidade**

- [ ] Título Valor da Unidade - 20 Bold azul cor #06024C
- [ ] backgroun azul cor #06024C, arredondado nas pontas (raio 10)
- [ ] Texto: Atual - 15 Bold cor branco
- [ ] Texto: Ùltima Aquisição  - 15 Bold cor branco
- [ ] Texto: Variação - 15 Bold cor branco
- [ ] Linah divisória com símbolo diodo no centro
- [ ] Gráfico de linha com média e histórico de valores 
- [ ] botões de filtro de período

**Card Fornecedores Cadastrados**

- [ ] Título Fornecedores Cadastrados - 25 Bold azul cor #06024C
- [ ] Tabela - background branco
- [ ] Tabela borda background #707070
- [ ] Tabela sombra background #707070 x5 y 5 d 1
- [ ] Cabeçalho da tabela: # / Fornecedor / Valor Unidade / Prazo / Última Compra / Visitar - 20 Bold azul cor #06024C
- [ ] Linhas com texto 15 Regular azul cor #06024C
- [ ] Efeito Hoover da linha - fundo Azul cor #06024C e texto branco 
- [ ] Barra de Rolagem 

### Rodapé
 - [ ] Logo DevQore

![13 - Compra de Material](https://user-images.githubusercontent.com/72522695/102415069-4f3ed080-3fd6-11eb-88f2-92705aef62e0.png)
