### ISSUE TITLE
4.00 Dashboard - layout

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#8]
### Menu Superior
- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo da Página
- [ ] Background Imagem Placa

**Cards Superiores**
1) Card Itens
- [ ] Logo itens
- [ ] Quantidade de itens e valores
- [ ] Background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] Efeito hoover

2) Card Equipamentos
- [ ] Logo itens
- [ ] Quantidade de itens e valores
- [ ] Background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] Efeito hoover

3) Card Usuários
- [ ] Logo itens
- [ ] Quantidade de itens e valores
- [ ] Background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] Efeito hoover

4) Card Fornecedores
- [ ] Logo itens
- [ ] Quantidade de itens e valores
- [ ] Background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] Efeito hoover

5) Card Clientes
- [ ] Logo itens
- [ ] Quantidade de itens e valores
- [ ] Background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] Efeito hoover

**Gráficos**
1) Gráfico Itens Consumidos - Top 10
- [ ] Gráfico alinhado a esquerda
- [ ] Título: Centralizado: Itens Consumidos - Top 10
- [ ] Icone Maximixar
- [ ] Icone Menu Gráfico
- [ ] Gráfico alinhado a esquerda
- [ ] Gráfico de Barra
- [ ] Background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

2) GráficoMovimentações
- [ ] Gráfico alinhado a esquerda
- [ ] Título: Movimentações
- [ ] Subtítulo: Itens e Valores
- [ ] Icone Maximixar
- [ ] Icone Menu Gráfico
- [ ] Gráfico alinhado a esquerda
- [ ] Gráfico Misto: Barras e linha
- [ ] Background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1

**Acessos Rápidos**
- [ ] Background roxo: #531D62
- [ ] Botão Pedido de Compra
- [ ] Botão Entrada de Componentes
- [ ] Botão Saída de Componentes
- [ ] Botão Empréstimo de Equipamentos
- [ ] Botão Cadastro de Item

**Tabelas**
Informações Gerais
- [ ] Background branco
- [ ] Borda do background:  #707070
- [ ] Sombra background:  #707070  x 5 y 5 d 1
- [ ] Paginação
- [ ] Botão Buscar
- [ ] Subtítulos: Solicitações de Retirada / Entradas / Saídas

1) Solicitações de Retirada
- [ ] Linhas Card Sol. Retirada - Nome Solicitante / Foto Solicitante / Descrição do Item / Categoria / Modelo / Data / ID / Codigo / Venda / OS / NF / Fornecedor /Quantidade
- [ ] Linhas Card Sol Retirada: Background branco
- [ ] Linhas Card Sol Retirada: Borda do background:  #707070
- [ ] Linhas Card Sol Retirada: Sombra background:  #707070  x 5 y 5 d 1
- [ ] Linhas Card Sol Retirada: Efeito Hoover
- [ ] Menu Linha Cards
- [ ] Maximizar

2) Entradas
- [ ] Linhas Card Entrada - Nome Solicitante / Foto Solicitante / Descrição do Item / Categoria / Modelo / Data / ID / Codigo / OS / NF / Fornecedor / Quantidade
- [ ] Menu Linha Cards
- [ ] Icone Entradas
- [ ] Paginação
- [ ] Botão Buscar
- [ ] Maximizar

3) Retiradas
- [ ] Linhas Card Entrada - Nome Solicitante / Foto Solicitante / Descrição do Item / Categoria / Modelo / Data / ID / Codigo / OS / Venda / NF / Fornecedor / Quantidade
- [ ] Menu Linha Cards
- [ ] Icone Retiradas
- [ ] Paginação
- [ ] Botão Buscar
- [ ] Maximizar

### Rodapé
- [ ] Logo DevQore

![04 - Dashboard](https://user-images.githubusercontent.com/72522695/102363792-87252400-3f94-11eb-9e24-77da6d2dd2ef.png)
