### ISSUE TITLE
4.01 Dashboard Itens Consumidos - Layout

### ISSUE THREAD

**Issue by hansmuller85** [esdrasli/urquiza#9]
### Menu Superior
- [ ]  logo alinhado a esquerda
- [ ]  Links Menu Central: Cadastro / Compra / Entrada / Retirada / Parceiros / Realtórios /
- [ ]  Background Azul Menu Central - cor #06024C
- [ ]  Links Menu Esquerda: icone Alertas / Usuário / Home
- [ ]  Background Roxo Menu Esquerda cor: #531D62

### Corpo Página
- [ ]  Botão Voltar com alinhamento superior direito e background: #531D62
- [ ]  Background Imagem Placa

**Calendário**
- [ ] Calendário alinhado a esquerda
- [ ] Ano alinhamento superior
- [ ] Meses (pode escolher vários ao mesmo tempo)
- [ ] Background branco
- [ ] Borda do background: #707070
- [ ] Sombra background: #707070 x 5 y 5 d 1

**Filtros - combobox**
 - [ ] Fornecedor 
 - [ ] Categoria
 - [ ] Marca
 - [ ] Modelo
 
**Gráfico Itens Consumidos**
- [ ] Alinhamento a direita
- [ ] Título Centralizado: Itens Consumidos
- [ ] Gráfico de barra com 20 itens
- [ ] Botão de busca
- [ ] Background branco
- [ ] Borda do background: #707070
- [ ] Sombra background: #707070 x 5 y 5 d 1

** Tabela Itens Consumidos**
- [ ] Alinhamento a direita
- [ ] Tabela: # / Item / ID / Código / Categoria / Marca / Modelo / Qte / Valor Unid / Total
- [ ] Barra de Rolagem 
- [ ] Background branco
- [ ] Borda do background: #707070
- [ ] Sombra background: #707070 x 5 y 5 d 1

### Rodapé

- [ ] Logo DevQore
![04 Dashboard Itens Consumidos](https://user-images.githubusercontent.com/72522695/102366038-f13ec880-3f96-11eb-877a-350872e9d8eb.png)
